# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
    typedb-behaviour: [build]
    typedb-protocol: [build, release]

build:
  correctness:
    benchmark-tpcc-typedb-verification:
      image: typedb-ubuntu-22.04
      machine: 16-core-64-gb
      command: |
        sleep 7200
        tool/postgres/install-driver.sh
        tool/postgres/install-server.sh
        tool/postgres/start-server.sh
        tool/install-typedb-driver.sh
        tool/start-typedb-core.sh
        sleep 7200
        # tool/execute-tpcc.sh --scalefactor=100 --warehouses=4 typedb3 --verify
        tool/stop-typedb-core.sh
        tool/postgres/stop-server.sh
    benchmark-tpcc-typedb:
      image: typedb-ubuntu-22.04
      machine: 16-core-64-gb
      command: |
        tool/install-typedb-driver.sh
        tool/start-typedb-core.sh
        tool/execute-tpcc.sh --scalefactor=100 --warehouses=4 typedb3
        tool/stop-typedb-core.sh
    benchmark-tpcc-mongodb:
      image: typedb-ubuntu-22.04
      machine: 16-core-64-gb
      command: |
        tool/mongodb/install-server.sh
        tool/mongodb/install-driver.sh
        tool/mongodb/start-server.sh
        tool/mongodb/init-replica-set.sh
        tool/execute-tpcc.sh --scalefactor=100 --warehouses=4 mongodb
        tool/mongodb/stop-server.sh