# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
    typedb-behaviour: [build]
    typedb-protocol: [build, release]

build:
  correctness:
    benchmark-tpcc-typedb:
      image: typedb-ubuntu-22.04
      machine: 16-core-64-gb
      command: |
        tool/install-typedb-driver.sh
        tool/start-typedb-core.sh
        tool/execute-tpcc.sh --scalefactor=0.5 --warehouses=2 typedb3 --duration=1200
        tool/stop-typedb-core.sh
        sleep 600
    benchmark-tpcc-mongodb:
      image: typedb-ubuntu-22.04
      machine: 16-core-64-gb
      command: |
        tool/mongodb/install-server.sh
        tool/mongodb/install-driver.sh
        tool/mongodb/start-server.sh
        tool/mongodb/init-replica-set.sh
        tool/execute-tpcc.sh --scalefactor=0.5 --warehouses=2 mongodb --duration=1200
        tool/mongodb/stop-server.sh
        sleep 600
